Traceback (most recent call last):
  File "/Users/fuzzbin/.pyenv/versions/3.10.4/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/fuzzbin/.pyenv/versions/3.10.4/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/fuzzbin/.pyenv/versions/3.10.4/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/fuzzbin/.pyenv/versions/3.10.4/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/fuzzbin/.pyenv/versions/3.10.4/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/fuzzbin/.pyenv/versions/3.10.4/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/fuzzbin/.pyenv/versions/3.10.4/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/fuzzbin/.pyenv/versions/3.10.4/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Importerer n√∏dvendige biblioteker
import matplotlib.pyplot as plt
import numpy as np

# Initialbetingelser
y0 = 1
delta_t = 1

# For hvilken t skal beregningene stoppe?
max_t = 5

# Eksakt l√∏sning
def A(x, k):
    return k * np.exp(x)

# Eulers metode for denne spesifikke problemstillingen
def next_y(t, yn):
    return yn + t * yn

# x-verdier for plotting av eksakt l√∏sning
x = np.arange(0, max_t, 0.1)
y = []

# Regner ut eksakt l√∏sning
for i in x:
    y.append(A(i, y0))

# x-verdier for plotting av Euler
xe = np.arange(0, max_t, delta_t).tolist()

# Initialiserer med startverdien for ye
ye = [y0] 

# Bruker Eulers metode for √• regne ut neste y-verdi
for verdi in xe:
    ye.append(next_y(delta_t, ye[-1]))

# Legger til den siste x-verdien
xe.append(xe[-1] + delta_t)

# Utskrift av data
plt.grid() # Lager rutenett
plt.xlabel('$t$') # Merker x-aksen
plt.ylabel('$A(t)$') # Merker y-aksen
plt.plot(x, y, label='$f(x)=e^x$')
plt.plot(xe, ye, label='Euler med $\Delta t={}$'.format(delta_t))
plt.legend()
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 2>[0;34m()[0m
[1;32m      1[0m [38;5;66;03m# Importerer n√∏dvendige biblioteker[39;00m
[0;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m      5[0m [38;5;66;03m# Initialbetingelser[39;00m

[0;31mModuleNotFoundError[0m: No module named 'matplotlib'
ModuleNotFoundError: No module named 'matplotlib'

